/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAccountingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimReserve"
      | "getAllTVLs"
      | "getJuniorAPY"
      | "getJuniorTVL"
      | "getMezzAPY"
      | "getSeniorAPY"
      | "getSeniorPrincipal"
      | "getTrancheTVL"
      | "recordDeposit"
      | "recordFee"
      | "recordWithdraw"
      | "updateTVL"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTVLs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJuniorAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJuniorTVL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMezzAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSeniorAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSeniorPrincipal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrancheTVL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordWithdraw",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTVL",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllTVLs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJuniorAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJuniorTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMezzAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSeniorAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSeniorPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrancheTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTVL", data: BytesLike): Result;
}

export interface IAccounting extends BaseContract {
  connect(runner?: ContractRunner | null): IAccounting;
  waitForDeployment(): Promise<this>;

  interface: IAccountingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimReserve: TypedContractMethod<[], [bigint], "nonpayable">;

  getAllTVLs: TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { sr: bigint; mz: bigint; jr: bigint }],
    "view"
  >;

  getJuniorAPY: TypedContractMethod<[], [bigint], "view">;

  getJuniorTVL: TypedContractMethod<[], [bigint], "view">;

  getMezzAPY: TypedContractMethod<[], [bigint], "view">;

  getSeniorAPY: TypedContractMethod<[], [bigint], "view">;

  getSeniorPrincipal: TypedContractMethod<[], [bigint], "view">;

  getTrancheTVL: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  recordDeposit: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordFee: TypedContractMethod<
    [id: BigNumberish, feeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordWithdraw: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTVL: TypedContractMethod<
    [currentStrategyTVL: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimReserve"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTVLs"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { sr: bigint; mz: bigint; jr: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJuniorAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJuniorTVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMezzAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSeniorAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSeniorPrincipal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrancheTVL"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDeposit"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordFee"
  ): TypedContractMethod<
    [id: BigNumberish, feeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordWithdraw"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTVL"
  ): TypedContractMethod<
    [currentStrategyTVL: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
