/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAprPairFeedSol from "./IAprPairFeed.sol";
export type { iAprPairFeedSol };
export type { IAccounting } from "./IAccounting";
export type { IAprFeed } from "./IAprFeed";
export type { ICooldownHandler } from "./ICooldownHandler";
export type { IPrimeCDO } from "./IPrimeCDO";
export type { IQuoterV2 } from "./IQuoterV2";
export type { IStrategy } from "./IStrategy";
export type { ISwapRouter } from "./ISwapRouter";
