/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type CDOWithdrawResultStruct = {
  isInstant: boolean;
  amountOut: BigNumberish;
  cooldownId: BigNumberish;
  cooldownHandler: AddressLike;
  unlockTime: BigNumberish;
  feeAmount: BigNumberish;
  appliedCooldownType: BigNumberish;
};

export type CDOWithdrawResultStructOutput = [
  isInstant: boolean,
  amountOut: bigint,
  cooldownId: bigint,
  cooldownHandler: string,
  unlockTime: bigint,
  feeAmount: bigint,
  appliedCooldownType: bigint
] & {
  isInstant: boolean;
  amountOut: bigint;
  cooldownId: bigint;
  cooldownHandler: string;
  unlockTime: bigint;
  feeAmount: bigint;
  appliedCooldownType: bigint;
};

export interface IPrimeCDOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accounting"
      | "claimSharesWithdraw"
      | "claimWithdraw"
      | "deposit"
      | "requestWithdraw"
      | "strategy"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accounting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimSharesWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWithdraw",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "strategy", values?: undefined): string;

  decodeFunctionResult(functionFragment: "accounting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimSharesWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategy", data: BytesLike): Result;
}

export interface IPrimeCDO extends BaseContract {
  connect(runner?: ContractRunner | null): IPrimeCDO;
  waitForDeployment(): Promise<this>;

  interface: IPrimeCDOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accounting: TypedContractMethod<[], [string], "view">;

  claimSharesWithdraw: TypedContractMethod<
    [cooldownId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  claimWithdraw: TypedContractMethod<
    [cooldownId: BigNumberish, cooldownHandler: AddressLike],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [tranche: BigNumberish, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  requestWithdraw: TypedContractMethod<
    [
      tranche: BigNumberish,
      baseAmount: BigNumberish,
      beneficiary: AddressLike,
      vaultShares: BigNumberish
    ],
    [CDOWithdrawResultStructOutput],
    "nonpayable"
  >;

  strategy: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accounting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimSharesWithdraw"
  ): TypedContractMethod<[cooldownId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWithdraw"
  ): TypedContractMethod<
    [cooldownId: BigNumberish, cooldownHandler: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [tranche: BigNumberish, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<
    [
      tranche: BigNumberish,
      baseAmount: BigNumberish,
      beneficiary: AddressLike,
      vaultShares: BigNumberish
    ],
    [CDOWithdrawResultStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "strategy"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
