/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RiskParams {
  export type PremiumCurveStruct = {
    x: BigNumberish;
    y: BigNumberish;
    k: BigNumberish;
  };

  export type PremiumCurveStructOutput = [x: bigint, y: bigint, k: bigint] & {
    x: bigint;
    y: bigint;
    k: bigint;
  };
}

export interface RiskParamsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_RESERVE_BPS"
      | "MAX_SENIOR_X"
      | "MAX_SENIOR_XY"
      | "acceptOwnership"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "s_reserveBps"
      | "s_seniorPremium"
      | "setReserveBps"
      | "setSeniorPremium"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "ReserveBpsUpdated"
      | "SeniorPremiumUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_RESERVE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SENIOR_X",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SENIOR_XY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_reserveBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_seniorPremium",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSeniorPremium",
    values: [RiskParams.PremiumCurveStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_RESERVE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SENIOR_X",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SENIOR_XY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_reserveBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_seniorPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSeniorPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveBpsUpdatedEvent {
  export type InputTuple = [reserveBps: BigNumberish];
  export type OutputTuple = [reserveBps: bigint];
  export interface OutputObject {
    reserveBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeniorPremiumUpdatedEvent {
  export type InputTuple = [x: BigNumberish, y: BigNumberish, k: BigNumberish];
  export type OutputTuple = [x: bigint, y: bigint, k: bigint];
  export interface OutputObject {
    x: bigint;
    y: bigint;
    k: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskParams extends BaseContract {
  connect(runner?: ContractRunner | null): RiskParams;
  waitForDeployment(): Promise<this>;

  interface: RiskParamsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_RESERVE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_SENIOR_X: TypedContractMethod<[], [bigint], "view">;

  MAX_SENIOR_XY: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  s_reserveBps: TypedContractMethod<[], [bigint], "view">;

  s_seniorPremium: TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { x: bigint; y: bigint; k: bigint }],
    "view"
  >;

  setReserveBps: TypedContractMethod<
    [reserveBps_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSeniorPremium: TypedContractMethod<
    [curve: RiskParams.PremiumCurveStruct],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_RESERVE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SENIOR_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SENIOR_XY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "s_reserveBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_seniorPremium"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { x: bigint; y: bigint; k: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setReserveBps"
  ): TypedContractMethod<[reserveBps_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSeniorPremium"
  ): TypedContractMethod<
    [curve: RiskParams.PremiumCurveStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveBpsUpdated"
  ): TypedContractEvent<
    ReserveBpsUpdatedEvent.InputTuple,
    ReserveBpsUpdatedEvent.OutputTuple,
    ReserveBpsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SeniorPremiumUpdated"
  ): TypedContractEvent<
    SeniorPremiumUpdatedEvent.InputTuple,
    SeniorPremiumUpdatedEvent.OutputTuple,
    SeniorPremiumUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReserveBpsUpdated(uint256)": TypedContractEvent<
      ReserveBpsUpdatedEvent.InputTuple,
      ReserveBpsUpdatedEvent.OutputTuple,
      ReserveBpsUpdatedEvent.OutputObject
    >;
    ReserveBpsUpdated: TypedContractEvent<
      ReserveBpsUpdatedEvent.InputTuple,
      ReserveBpsUpdatedEvent.OutputTuple,
      ReserveBpsUpdatedEvent.OutputObject
    >;

    "SeniorPremiumUpdated(uint256,uint256,uint256)": TypedContractEvent<
      SeniorPremiumUpdatedEvent.InputTuple,
      SeniorPremiumUpdatedEvent.OutputTuple,
      SeniorPremiumUpdatedEvent.OutputObject
    >;
    SeniorPremiumUpdated: TypedContractEvent<
      SeniorPremiumUpdatedEvent.InputTuple,
      SeniorPremiumUpdatedEvent.OutputTuple,
      SeniorPremiumUpdatedEvent.OutputObject
    >;
  };
}
