/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccountingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRECISION"
      | "claimReserve"
      | "getAllTVLs"
      | "getJuniorAPY"
      | "getJuniorTVL"
      | "getMezzAPY"
      | "getSeniorAPY"
      | "getSeniorPrincipal"
      | "getTrancheTVL"
      | "i_aprFeed"
      | "i_riskParams"
      | "recordDeposit"
      | "recordFee"
      | "recordWithdraw"
      | "s_juniorBaseTVL"
      | "s_lastUpdateTimestamp"
      | "s_mezzTVL"
      | "s_mzTargetIndex"
      | "s_primeCDO"
      | "s_reserveTVL"
      | "s_seniorPrincipal"
      | "s_seniorTVL"
      | "s_srtTargetIndex"
      | "setCDO"
      | "updateTVL"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CDOSet"
      | "DepositRecorded"
      | "FeeRecorded"
      | "GainSplit"
      | "LossApplied"
      | "SeniorPrincipalAbsorbed"
      | "SeniorPrincipalIncreased"
      | "SeniorPrincipalScaled"
      | "WithdrawRecorded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTVLs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJuniorAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJuniorTVL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMezzAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSeniorAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSeniorPrincipal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrancheTVL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "i_aprFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "i_riskParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordWithdraw",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_juniorBaseTVL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_lastUpdateTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "s_mezzTVL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_mzTargetIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_primeCDO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_reserveTVL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_seniorPrincipal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_seniorTVL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_srtTargetIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setCDO", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "updateTVL",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllTVLs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJuniorAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJuniorTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMezzAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSeniorAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSeniorPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrancheTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_aprFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_riskParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_juniorBaseTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_lastUpdateTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_mezzTVL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_mzTargetIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_primeCDO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_reserveTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_seniorPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_seniorTVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_srtTargetIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCDO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateTVL", data: BytesLike): Result;
}

export namespace CDOSetEvent {
  export type InputTuple = [cdo: AddressLike];
  export type OutputTuple = [cdo: string];
  export interface OutputObject {
    cdo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRecordedEvent {
  export type InputTuple = [tranche: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [tranche: bigint, amount: bigint];
  export interface OutputObject {
    tranche: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecordedEvent {
  export type InputTuple = [tranche: BigNumberish, feeAmount: BigNumberish];
  export type OutputTuple = [tranche: bigint, feeAmount: bigint];
  export interface OutputObject {
    tranche: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GainSplitEvent {
  export type InputTuple = [
    netGain: BigNumberish,
    seniorGain: BigNumberish,
    mezzGain: BigNumberish,
    juniorGain: BigNumberish,
    reserveCut: BigNumberish
  ];
  export type OutputTuple = [
    netGain: bigint,
    seniorGain: bigint,
    mezzGain: bigint,
    juniorGain: bigint,
    reserveCut: bigint
  ];
  export interface OutputObject {
    netGain: bigint;
    seniorGain: bigint;
    mezzGain: bigint;
    juniorGain: bigint;
    reserveCut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LossAppliedEvent {
  export type InputTuple = [
    loss: BigNumberish,
    jrAbsorbed: BigNumberish,
    mzAbsorbed: BigNumberish,
    srYieldAbsorbed: BigNumberish,
    srPrincipalAbsorbed: BigNumberish
  ];
  export type OutputTuple = [
    loss: bigint,
    jrAbsorbed: bigint,
    mzAbsorbed: bigint,
    srYieldAbsorbed: bigint,
    srPrincipalAbsorbed: bigint
  ];
  export interface OutputObject {
    loss: bigint;
    jrAbsorbed: bigint;
    mzAbsorbed: bigint;
    srYieldAbsorbed: bigint;
    srPrincipalAbsorbed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeniorPrincipalAbsorbedEvent {
  export type InputTuple = [amount: BigNumberish, newPrincipal: BigNumberish];
  export type OutputTuple = [amount: bigint, newPrincipal: bigint];
  export interface OutputObject {
    amount: bigint;
    newPrincipal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeniorPrincipalIncreasedEvent {
  export type InputTuple = [amount: BigNumberish, newPrincipal: BigNumberish];
  export type OutputTuple = [amount: bigint, newPrincipal: bigint];
  export interface OutputObject {
    amount: bigint;
    newPrincipal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeniorPrincipalScaledEvent {
  export type InputTuple = [
    oldTVL: BigNumberish,
    newTVL: BigNumberish,
    newPrincipal: BigNumberish
  ];
  export type OutputTuple = [
    oldTVL: bigint,
    newTVL: bigint,
    newPrincipal: bigint
  ];
  export interface OutputObject {
    oldTVL: bigint;
    newTVL: bigint;
    newPrincipal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawRecordedEvent {
  export type InputTuple = [tranche: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [tranche: bigint, amount: bigint];
  export interface OutputObject {
    tranche: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Accounting extends BaseContract {
  connect(runner?: ContractRunner | null): Accounting;
  waitForDeployment(): Promise<this>;

  interface: AccountingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  claimReserve: TypedContractMethod<[], [bigint], "nonpayable">;

  getAllTVLs: TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { sr: bigint; mz: bigint; jr: bigint }],
    "view"
  >;

  getJuniorAPY: TypedContractMethod<[], [bigint], "view">;

  getJuniorTVL: TypedContractMethod<[], [bigint], "view">;

  getMezzAPY: TypedContractMethod<[], [bigint], "view">;

  getSeniorAPY: TypedContractMethod<[], [bigint], "view">;

  getSeniorPrincipal: TypedContractMethod<[], [bigint], "view">;

  getTrancheTVL: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  i_aprFeed: TypedContractMethod<[], [string], "view">;

  i_riskParams: TypedContractMethod<[], [string], "view">;

  recordDeposit: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordFee: TypedContractMethod<
    [id: BigNumberish, feeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordWithdraw: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  s_juniorBaseTVL: TypedContractMethod<[], [bigint], "view">;

  s_lastUpdateTimestamp: TypedContractMethod<[], [bigint], "view">;

  s_mezzTVL: TypedContractMethod<[], [bigint], "view">;

  s_mzTargetIndex: TypedContractMethod<[], [bigint], "view">;

  s_primeCDO: TypedContractMethod<[], [string], "view">;

  s_reserveTVL: TypedContractMethod<[], [bigint], "view">;

  s_seniorPrincipal: TypedContractMethod<[], [bigint], "view">;

  s_seniorTVL: TypedContractMethod<[], [bigint], "view">;

  s_srtTargetIndex: TypedContractMethod<[], [bigint], "view">;

  setCDO: TypedContractMethod<[cdo_: AddressLike], [void], "nonpayable">;

  updateTVL: TypedContractMethod<
    [currentStrategyTVL: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReserve"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTVLs"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { sr: bigint; mz: bigint; jr: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJuniorAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJuniorTVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMezzAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSeniorAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSeniorPrincipal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrancheTVL"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_aprFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_riskParams"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDeposit"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordFee"
  ): TypedContractMethod<
    [id: BigNumberish, feeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordWithdraw"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "s_juniorBaseTVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_lastUpdateTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_mezzTVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_mzTargetIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_primeCDO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "s_reserveTVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_seniorPrincipal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_seniorTVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_srtTargetIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setCDO"
  ): TypedContractMethod<[cdo_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTVL"
  ): TypedContractMethod<
    [currentStrategyTVL: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CDOSet"
  ): TypedContractEvent<
    CDOSetEvent.InputTuple,
    CDOSetEvent.OutputTuple,
    CDOSetEvent.OutputObject
  >;
  getEvent(
    key: "DepositRecorded"
  ): TypedContractEvent<
    DepositRecordedEvent.InputTuple,
    DepositRecordedEvent.OutputTuple,
    DepositRecordedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecorded"
  ): TypedContractEvent<
    FeeRecordedEvent.InputTuple,
    FeeRecordedEvent.OutputTuple,
    FeeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "GainSplit"
  ): TypedContractEvent<
    GainSplitEvent.InputTuple,
    GainSplitEvent.OutputTuple,
    GainSplitEvent.OutputObject
  >;
  getEvent(
    key: "LossApplied"
  ): TypedContractEvent<
    LossAppliedEvent.InputTuple,
    LossAppliedEvent.OutputTuple,
    LossAppliedEvent.OutputObject
  >;
  getEvent(
    key: "SeniorPrincipalAbsorbed"
  ): TypedContractEvent<
    SeniorPrincipalAbsorbedEvent.InputTuple,
    SeniorPrincipalAbsorbedEvent.OutputTuple,
    SeniorPrincipalAbsorbedEvent.OutputObject
  >;
  getEvent(
    key: "SeniorPrincipalIncreased"
  ): TypedContractEvent<
    SeniorPrincipalIncreasedEvent.InputTuple,
    SeniorPrincipalIncreasedEvent.OutputTuple,
    SeniorPrincipalIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "SeniorPrincipalScaled"
  ): TypedContractEvent<
    SeniorPrincipalScaledEvent.InputTuple,
    SeniorPrincipalScaledEvent.OutputTuple,
    SeniorPrincipalScaledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawRecorded"
  ): TypedContractEvent<
    WithdrawRecordedEvent.InputTuple,
    WithdrawRecordedEvent.OutputTuple,
    WithdrawRecordedEvent.OutputObject
  >;

  filters: {
    "CDOSet(address)": TypedContractEvent<
      CDOSetEvent.InputTuple,
      CDOSetEvent.OutputTuple,
      CDOSetEvent.OutputObject
    >;
    CDOSet: TypedContractEvent<
      CDOSetEvent.InputTuple,
      CDOSetEvent.OutputTuple,
      CDOSetEvent.OutputObject
    >;

    "DepositRecorded(uint8,uint256)": TypedContractEvent<
      DepositRecordedEvent.InputTuple,
      DepositRecordedEvent.OutputTuple,
      DepositRecordedEvent.OutputObject
    >;
    DepositRecorded: TypedContractEvent<
      DepositRecordedEvent.InputTuple,
      DepositRecordedEvent.OutputTuple,
      DepositRecordedEvent.OutputObject
    >;

    "FeeRecorded(uint8,uint256)": TypedContractEvent<
      FeeRecordedEvent.InputTuple,
      FeeRecordedEvent.OutputTuple,
      FeeRecordedEvent.OutputObject
    >;
    FeeRecorded: TypedContractEvent<
      FeeRecordedEvent.InputTuple,
      FeeRecordedEvent.OutputTuple,
      FeeRecordedEvent.OutputObject
    >;

    "GainSplit(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      GainSplitEvent.InputTuple,
      GainSplitEvent.OutputTuple,
      GainSplitEvent.OutputObject
    >;
    GainSplit: TypedContractEvent<
      GainSplitEvent.InputTuple,
      GainSplitEvent.OutputTuple,
      GainSplitEvent.OutputObject
    >;

    "LossApplied(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LossAppliedEvent.InputTuple,
      LossAppliedEvent.OutputTuple,
      LossAppliedEvent.OutputObject
    >;
    LossApplied: TypedContractEvent<
      LossAppliedEvent.InputTuple,
      LossAppliedEvent.OutputTuple,
      LossAppliedEvent.OutputObject
    >;

    "SeniorPrincipalAbsorbed(uint256,uint256)": TypedContractEvent<
      SeniorPrincipalAbsorbedEvent.InputTuple,
      SeniorPrincipalAbsorbedEvent.OutputTuple,
      SeniorPrincipalAbsorbedEvent.OutputObject
    >;
    SeniorPrincipalAbsorbed: TypedContractEvent<
      SeniorPrincipalAbsorbedEvent.InputTuple,
      SeniorPrincipalAbsorbedEvent.OutputTuple,
      SeniorPrincipalAbsorbedEvent.OutputObject
    >;

    "SeniorPrincipalIncreased(uint256,uint256)": TypedContractEvent<
      SeniorPrincipalIncreasedEvent.InputTuple,
      SeniorPrincipalIncreasedEvent.OutputTuple,
      SeniorPrincipalIncreasedEvent.OutputObject
    >;
    SeniorPrincipalIncreased: TypedContractEvent<
      SeniorPrincipalIncreasedEvent.InputTuple,
      SeniorPrincipalIncreasedEvent.OutputTuple,
      SeniorPrincipalIncreasedEvent.OutputObject
    >;

    "SeniorPrincipalScaled(uint256,uint256,uint256)": TypedContractEvent<
      SeniorPrincipalScaledEvent.InputTuple,
      SeniorPrincipalScaledEvent.OutputTuple,
      SeniorPrincipalScaledEvent.OutputObject
    >;
    SeniorPrincipalScaled: TypedContractEvent<
      SeniorPrincipalScaledEvent.InputTuple,
      SeniorPrincipalScaledEvent.OutputTuple,
      SeniorPrincipalScaledEvent.OutputObject
    >;

    "WithdrawRecorded(uint8,uint256)": TypedContractEvent<
      WithdrawRecordedEvent.InputTuple,
      WithdrawRecordedEvent.OutputTuple,
      WithdrawRecordedEvent.OutputObject
    >;
    WithdrawRecorded: TypedContractEvent<
      WithdrawRecordedEvent.InputTuple,
      WithdrawRecordedEvent.OutputTuple,
      WithdrawRecordedEvent.OutputObject
    >;
  };
}
