/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PrimeLock__factory } from "./PrimeLock__factory";
export { RiskParams__factory } from "./RiskParams__factory";
