/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IAprPairFeed {
  export type TRoundStruct = {
    aprTargetSenior: BigNumberish;
    aprTargetMezz: BigNumberish;
    aprBase: BigNumberish;
    updatedAt: BigNumberish;
    answeredInRound: BigNumberish;
  };

  export type TRoundStructOutput = [
    aprTargetSenior: bigint,
    aprTargetMezz: bigint,
    aprBase: bigint,
    updatedAt: bigint,
    answeredInRound: bigint
  ] & {
    aprTargetSenior: bigint;
    aprTargetMezz: bigint;
    aprBase: bigint;
    updatedAt: bigint;
    answeredInRound: bigint;
  };
}

export interface MockAprFeedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRoundData"
      | "latestRoundData"
      | "pushAprBase"
      | "pushAprTarget"
      | "setAprs"
      | "setAprsPerTranche"
      | "updateRoundData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRoundData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRoundData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushAprBase",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pushAprTarget",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAprs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAprsPerTranche",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoundData",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushAprBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushAprTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAprs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAprsPerTranche",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoundData",
    data: BytesLike
  ): Result;
}

export interface MockAprFeed extends BaseContract {
  connect(runner?: ContractRunner | null): MockAprFeed;
  waitForDeployment(): Promise<this>;

  interface: MockAprFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRoundData: TypedContractMethod<
    [arg0: BigNumberish],
    [IAprPairFeed.TRoundStructOutput],
    "view"
  >;

  latestRoundData: TypedContractMethod<
    [],
    [IAprPairFeed.TRoundStructOutput],
    "view"
  >;

  pushAprBase: TypedContractMethod<
    [value: BigNumberish, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  pushAprTarget: TypedContractMethod<
    [tranche: BigNumberish, value: BigNumberish, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAprs: TypedContractMethod<
    [aprTarget_: BigNumberish, aprBase_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAprsPerTranche: TypedContractMethod<
    [
      aprTargetSenior_: BigNumberish,
      aprTargetMezz_: BigNumberish,
      aprBase_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateRoundData: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRoundData"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [IAprPairFeed.TRoundStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestRoundData"
  ): TypedContractMethod<[], [IAprPairFeed.TRoundStructOutput], "view">;
  getFunction(
    nameOrSignature: "pushAprBase"
  ): TypedContractMethod<
    [value: BigNumberish, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pushAprTarget"
  ): TypedContractMethod<
    [tranche: BigNumberish, value: BigNumberish, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAprs"
  ): TypedContractMethod<
    [aprTarget_: BigNumberish, aprBase_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAprsPerTranche"
  ): TypedContractMethod<
    [
      aprTargetSenior_: BigNumberish,
      aprTargetMezz_: BigNumberish,
      aprBase_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRoundData"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
