/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface SUSDaiAprPairProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "benchmarkTokenCount"
      | "getAprPair"
      | "getAprPairView"
      | "i_aavePool"
      | "i_vault"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "s_aprFeed"
      | "s_benchmarkTokens"
      | "s_latestSnapshot"
      | "s_prevSnapshot"
      | "setAprFeed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AprFeedSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "SnapshotShifted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "benchmarkTokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAprPair",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAprPairView",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_aavePool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_vault", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "s_aprFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_benchmarkTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_latestSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_prevSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAprFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "benchmarkTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAprPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAprPairView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_aavePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "i_vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_aprFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_benchmarkTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_latestSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_prevSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAprFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AprFeedSetEvent {
  export type InputTuple = [aprFeed: AddressLike];
  export type OutputTuple = [aprFeed: string];
  export interface OutputObject {
    aprFeed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotShiftedEvent {
  export type InputTuple = [
    prevRate: BigNumberish,
    newRate: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    prevRate: bigint,
    newRate: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    prevRate: bigint;
    newRate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SUSDaiAprPairProvider extends BaseContract {
  connect(runner?: ContractRunner | null): SUSDaiAprPairProvider;
  waitForDeployment(): Promise<this>;

  interface: SUSDaiAprPairProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  benchmarkTokenCount: TypedContractMethod<[], [bigint], "view">;

  getAprPair: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        aprTarget: bigint;
        aprBase: bigint;
        timestamp: bigint;
      }
    ],
    "nonpayable"
  >;

  getAprPairView: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        aprTarget: bigint;
        aprBase: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  i_aavePool: TypedContractMethod<[], [string], "view">;

  i_vault: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  s_aprFeed: TypedContractMethod<[], [string], "view">;

  s_benchmarkTokens: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  s_latestSnapshot: TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;

  s_prevSnapshot: TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;

  setAprFeed: TypedContractMethod<
    [aprFeed_: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "benchmarkTokenCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAprPair"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        aprTarget: bigint;
        aprBase: bigint;
        timestamp: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAprPairView"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        aprTarget: bigint;
        aprBase: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "i_aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "s_aprFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "s_benchmarkTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "s_latestSnapshot"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "s_prevSnapshot"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAprFeed"
  ): TypedContractMethod<[aprFeed_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AprFeedSet"
  ): TypedContractEvent<
    AprFeedSetEvent.InputTuple,
    AprFeedSetEvent.OutputTuple,
    AprFeedSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SnapshotShifted"
  ): TypedContractEvent<
    SnapshotShiftedEvent.InputTuple,
    SnapshotShiftedEvent.OutputTuple,
    SnapshotShiftedEvent.OutputObject
  >;

  filters: {
    "AprFeedSet(address)": TypedContractEvent<
      AprFeedSetEvent.InputTuple,
      AprFeedSetEvent.OutputTuple,
      AprFeedSetEvent.OutputObject
    >;
    AprFeedSet: TypedContractEvent<
      AprFeedSetEvent.InputTuple,
      AprFeedSetEvent.OutputTuple,
      AprFeedSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SnapshotShifted(uint256,uint256,uint256)": TypedContractEvent<
      SnapshotShiftedEvent.InputTuple,
      SnapshotShiftedEvent.OutputTuple,
      SnapshotShiftedEvent.OutputObject
    >;
    SnapshotShifted: TypedContractEvent<
      SnapshotShiftedEvent.InputTuple,
      SnapshotShiftedEvent.OutputTuple,
      SnapshotShiftedEvent.OutputObject
    >;
  };
}
