/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type CDOWithdrawResultStruct = {
  isInstant: boolean;
  amountOut: BigNumberish;
  cooldownId: BigNumberish;
  cooldownHandler: AddressLike;
  unlockTime: BigNumberish;
  feeAmount: BigNumberish;
  appliedCooldownType: BigNumberish;
};

export type CDOWithdrawResultStructOutput = [
  isInstant: boolean,
  amountOut: bigint,
  cooldownId: bigint,
  cooldownHandler: string,
  unlockTime: bigint,
  feeAmount: bigint,
  appliedCooldownType: bigint
] & {
  isInstant: boolean;
  amountOut: bigint;
  cooldownId: bigint;
  cooldownHandler: string;
  unlockTime: bigint;
  feeAmount: bigint;
  appliedCooldownType: bigint;
};

export interface PrimeCDOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRECISION"
      | "acceptOwnership"
      | "accounting"
      | "claimReserve"
      | "claimSharesWithdraw"
      | "claimWithdraw"
      | "deposit"
      | "i_accounting"
      | "i_aprFeed"
      | "i_erc20Cooldown"
      | "i_outputToken"
      | "i_redemptionPolicy"
      | "i_sharesCooldown"
      | "i_strategy"
      | "owner"
      | "pendingOwner"
      | "registerTranche"
      | "renounceOwnership"
      | "requestWithdraw"
      | "s_juniorShortfallPausePrice"
      | "s_minCoverageForDeposit"
      | "s_shortfallPaused"
      | "s_tranches"
      | "s_vaultToTranche"
      | "setJuniorShortfallPausePrice"
      | "setMinCoverageForDeposit"
      | "strategy"
      | "transferOwnership"
      | "unpauseShortfall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "ShortfallPauseTriggered"
      | "ShortfallUnpaused"
      | "TrancheRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accounting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimSharesWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWithdraw",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "i_accounting",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_aprFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "i_erc20Cooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_outputToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_redemptionPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_sharesCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_strategy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerTranche",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_juniorShortfallPausePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_minCoverageForDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_shortfallPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_tranches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_vaultToTranche",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setJuniorShortfallPausePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinCoverageForDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "strategy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseShortfall",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "accounting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSharesWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_accounting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_aprFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_erc20Cooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_outputToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_redemptionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_sharesCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_strategy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTranche",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_juniorShortfallPausePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_minCoverageForDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_shortfallPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_tranches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_vaultToTranche",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setJuniorShortfallPausePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinCoverageForDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseShortfall",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShortfallPauseTriggeredEvent {
  export type InputTuple = [
    pricePerShare: BigNumberish,
    threshold: BigNumberish
  ];
  export type OutputTuple = [pricePerShare: bigint, threshold: bigint];
  export interface OutputObject {
    pricePerShare: bigint;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShortfallUnpausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrancheRegisteredEvent {
  export type InputTuple = [tranche: BigNumberish, vault: AddressLike];
  export type OutputTuple = [tranche: bigint, vault: string];
  export interface OutputObject {
    tranche: bigint;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrimeCDO extends BaseContract {
  connect(runner?: ContractRunner | null): PrimeCDO;
  waitForDeployment(): Promise<this>;

  interface: PrimeCDOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  accounting: TypedContractMethod<[], [string], "view">;

  claimReserve: TypedContractMethod<[], [bigint], "nonpayable">;

  claimSharesWithdraw: TypedContractMethod<
    [cooldownId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  claimWithdraw: TypedContractMethod<
    [cooldownId: BigNumberish, cooldownHandler: AddressLike],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [tranche: BigNumberish, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  i_accounting: TypedContractMethod<[], [string], "view">;

  i_aprFeed: TypedContractMethod<[], [string], "view">;

  i_erc20Cooldown: TypedContractMethod<[], [string], "view">;

  i_outputToken: TypedContractMethod<[], [string], "view">;

  i_redemptionPolicy: TypedContractMethod<[], [string], "view">;

  i_sharesCooldown: TypedContractMethod<[], [string], "view">;

  i_strategy: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  registerTranche: TypedContractMethod<
    [id: BigNumberish, vault: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestWithdraw: TypedContractMethod<
    [
      tranche: BigNumberish,
      baseAmount: BigNumberish,
      beneficiary: AddressLike,
      vaultShares: BigNumberish
    ],
    [CDOWithdrawResultStructOutput],
    "nonpayable"
  >;

  s_juniorShortfallPausePrice: TypedContractMethod<[], [bigint], "view">;

  s_minCoverageForDeposit: TypedContractMethod<[], [bigint], "view">;

  s_shortfallPaused: TypedContractMethod<[], [boolean], "view">;

  s_tranches: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  s_vaultToTranche: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setJuniorShortfallPausePrice: TypedContractMethod<
    [price: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinCoverageForDeposit: TypedContractMethod<
    [minCoverage: BigNumberish],
    [void],
    "nonpayable"
  >;

  strategy: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseShortfall: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "accounting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimReserve"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimSharesWithdraw"
  ): TypedContractMethod<[cooldownId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWithdraw"
  ): TypedContractMethod<
    [cooldownId: BigNumberish, cooldownHandler: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [tranche: BigNumberish, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "i_accounting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_aprFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_erc20Cooldown"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_outputToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_redemptionPolicy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_sharesCooldown"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_strategy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerTranche"
  ): TypedContractMethod<
    [id: BigNumberish, vault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<
    [
      tranche: BigNumberish,
      baseAmount: BigNumberish,
      beneficiary: AddressLike,
      vaultShares: BigNumberish
    ],
    [CDOWithdrawResultStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "s_juniorShortfallPausePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_minCoverageForDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_shortfallPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "s_tranches"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "s_vaultToTranche"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setJuniorShortfallPausePrice"
  ): TypedContractMethod<[price: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinCoverageForDeposit"
  ): TypedContractMethod<[minCoverage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "strategy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseShortfall"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ShortfallPauseTriggered"
  ): TypedContractEvent<
    ShortfallPauseTriggeredEvent.InputTuple,
    ShortfallPauseTriggeredEvent.OutputTuple,
    ShortfallPauseTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "ShortfallUnpaused"
  ): TypedContractEvent<
    ShortfallUnpausedEvent.InputTuple,
    ShortfallUnpausedEvent.OutputTuple,
    ShortfallUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "TrancheRegistered"
  ): TypedContractEvent<
    TrancheRegisteredEvent.InputTuple,
    TrancheRegisteredEvent.OutputTuple,
    TrancheRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ShortfallPauseTriggered(uint256,uint256)": TypedContractEvent<
      ShortfallPauseTriggeredEvent.InputTuple,
      ShortfallPauseTriggeredEvent.OutputTuple,
      ShortfallPauseTriggeredEvent.OutputObject
    >;
    ShortfallPauseTriggered: TypedContractEvent<
      ShortfallPauseTriggeredEvent.InputTuple,
      ShortfallPauseTriggeredEvent.OutputTuple,
      ShortfallPauseTriggeredEvent.OutputObject
    >;

    "ShortfallUnpaused()": TypedContractEvent<
      ShortfallUnpausedEvent.InputTuple,
      ShortfallUnpausedEvent.OutputTuple,
      ShortfallUnpausedEvent.OutputObject
    >;
    ShortfallUnpaused: TypedContractEvent<
      ShortfallUnpausedEvent.InputTuple,
      ShortfallUnpausedEvent.OutputTuple,
      ShortfallUnpausedEvent.OutputObject
    >;

    "TrancheRegistered(uint8,address)": TypedContractEvent<
      TrancheRegisteredEvent.InputTuple,
      TrancheRegisteredEvent.OutputTuple,
      TrancheRegisteredEvent.OutputObject
    >;
    TrancheRegistered: TypedContractEvent<
      TrancheRegisteredEvent.InputTuple,
      TrancheRegisteredEvent.OutputTuple,
      TrancheRegisteredEvent.OutputObject
    >;
  };
}
