/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace PrimeLens {
  export type TrancheInfoStruct = {
    trancheId: BigNumberish;
    vault: AddressLike;
    name: string;
    symbol: string;
    totalAssets: BigNumberish;
    totalSupply: BigNumberish;
    sharePrice: BigNumberish;
    apy: BigNumberish;
  };

  export type TrancheInfoStructOutput = [
    trancheId: bigint,
    vault: string,
    name: string,
    symbol: string,
    totalAssets: bigint,
    totalSupply: bigint,
    sharePrice: bigint,
    apy: bigint
  ] & {
    trancheId: bigint;
    vault: string;
    name: string;
    symbol: string;
    totalAssets: bigint;
    totalSupply: bigint;
    sharePrice: bigint;
    apy: bigint;
  };

  export type PendingWithdrawStruct = {
    requestId: BigNumberish;
    handler: AddressLike;
    beneficiary: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    unlockTime: BigNumberish;
    status: BigNumberish;
    isClaimable: boolean;
    timeRemaining: BigNumberish;
  };

  export type PendingWithdrawStructOutput = [
    requestId: bigint,
    handler: string,
    beneficiary: string,
    token: string,
    amount: bigint,
    unlockTime: bigint,
    status: bigint,
    isClaimable: boolean,
    timeRemaining: bigint
  ] & {
    requestId: bigint;
    handler: string;
    beneficiary: string;
    token: string;
    amount: bigint;
    unlockTime: bigint;
    status: bigint;
    isClaimable: boolean;
    timeRemaining: bigint;
  };

  export type ProtocolHealthStruct = {
    seniorTVL: BigNumberish;
    seniorPrincipal: BigNumberish;
    seniorYield: BigNumberish;
    juniorTVL: BigNumberish;
    totalTVL: BigNumberish;
    coverageSenior: BigNumberish;
    minCoverageForDeposit: BigNumberish;
    shortfallPaused: boolean;
    juniorShortfallPausePrice: BigNumberish;
    strategyTVL: BigNumberish;
  };

  export type ProtocolHealthStructOutput = [
    seniorTVL: bigint,
    seniorPrincipal: bigint,
    seniorYield: bigint,
    juniorTVL: bigint,
    totalTVL: bigint,
    coverageSenior: bigint,
    minCoverageForDeposit: bigint,
    shortfallPaused: boolean,
    juniorShortfallPausePrice: bigint,
    strategyTVL: bigint
  ] & {
    seniorTVL: bigint;
    seniorPrincipal: bigint;
    seniorYield: bigint;
    juniorTVL: bigint;
    totalTVL: bigint;
    coverageSenior: bigint;
    minCoverageForDeposit: bigint;
    shortfallPaused: boolean;
    juniorShortfallPausePrice: bigint;
    strategyTVL: bigint;
  };

  export type WithdrawConditionStruct = {
    mechanism: BigNumberish;
    feeBps: BigNumberish;
    cooldownDuration: BigNumberish;
    coverageSenior: BigNumberish;
  };

  export type WithdrawConditionStructOutput = [
    mechanism: bigint,
    feeBps: bigint,
    cooldownDuration: bigint,
    coverageSenior: bigint
  ] & {
    mechanism: bigint;
    feeBps: bigint;
    cooldownDuration: bigint;
    coverageSenior: bigint;
  };
}

export interface PrimeLensInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllTranches"
      | "getClaimableWithdraws"
      | "getProtocolHealth"
      | "getTrancheInfo"
      | "getUserPendingWithdraws"
      | "i_accounting"
      | "i_cdo"
      | "i_erc20Cooldown"
      | "i_juniorVault"
      | "i_redemptionPolicy"
      | "i_seniorVault"
      | "i_sharesCooldown"
      | "i_strategy"
      | "previewWithdrawCondition"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllTranches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableWithdraws",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolHealth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrancheInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPendingWithdraws",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "i_accounting",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_cdo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "i_erc20Cooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_juniorVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_redemptionPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_seniorVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_sharesCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_strategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewWithdrawCondition",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllTranches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableWithdraws",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolHealth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrancheInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPendingWithdraws",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_accounting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_cdo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_erc20Cooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_juniorVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_redemptionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_seniorVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_sharesCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_strategy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewWithdrawCondition",
    data: BytesLike
  ): Result;
}

export interface PrimeLens extends BaseContract {
  connect(runner?: ContractRunner | null): PrimeLens;
  waitForDeployment(): Promise<this>;

  interface: PrimeLensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllTranches: TypedContractMethod<
    [],
    [
      [PrimeLens.TrancheInfoStructOutput, PrimeLens.TrancheInfoStructOutput] & {
        senior: PrimeLens.TrancheInfoStructOutput;
        junior: PrimeLens.TrancheInfoStructOutput;
      }
    ],
    "view"
  >;

  getClaimableWithdraws: TypedContractMethod<
    [user: AddressLike],
    [PrimeLens.PendingWithdrawStructOutput[]],
    "view"
  >;

  getProtocolHealth: TypedContractMethod<
    [],
    [PrimeLens.ProtocolHealthStructOutput],
    "view"
  >;

  getTrancheInfo: TypedContractMethod<
    [tranche: BigNumberish],
    [PrimeLens.TrancheInfoStructOutput],
    "view"
  >;

  getUserPendingWithdraws: TypedContractMethod<
    [user: AddressLike],
    [PrimeLens.PendingWithdrawStructOutput[]],
    "view"
  >;

  i_accounting: TypedContractMethod<[], [string], "view">;

  i_cdo: TypedContractMethod<[], [string], "view">;

  i_erc20Cooldown: TypedContractMethod<[], [string], "view">;

  i_juniorVault: TypedContractMethod<[], [string], "view">;

  i_redemptionPolicy: TypedContractMethod<[], [string], "view">;

  i_seniorVault: TypedContractMethod<[], [string], "view">;

  i_sharesCooldown: TypedContractMethod<[], [string], "view">;

  i_strategy: TypedContractMethod<[], [string], "view">;

  previewWithdrawCondition: TypedContractMethod<
    [tranche: BigNumberish],
    [PrimeLens.WithdrawConditionStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllTranches"
  ): TypedContractMethod<
    [],
    [
      [PrimeLens.TrancheInfoStructOutput, PrimeLens.TrancheInfoStructOutput] & {
        senior: PrimeLens.TrancheInfoStructOutput;
        junior: PrimeLens.TrancheInfoStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimableWithdraws"
  ): TypedContractMethod<
    [user: AddressLike],
    [PrimeLens.PendingWithdrawStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolHealth"
  ): TypedContractMethod<[], [PrimeLens.ProtocolHealthStructOutput], "view">;
  getFunction(
    nameOrSignature: "getTrancheInfo"
  ): TypedContractMethod<
    [tranche: BigNumberish],
    [PrimeLens.TrancheInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPendingWithdraws"
  ): TypedContractMethod<
    [user: AddressLike],
    [PrimeLens.PendingWithdrawStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "i_accounting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_cdo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_erc20Cooldown"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_juniorVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_redemptionPolicy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_seniorVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_sharesCooldown"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_strategy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewWithdrawCondition"
  ): TypedContractMethod<
    [tranche: BigNumberish],
    [PrimeLens.WithdrawConditionStructOutput],
    "view"
  >;

  filters: {};
}
