/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usdai from "./usdai";
export type { usdai };
export type { BaseStrategy } from "./BaseStrategy";
